# Pull base image
FROM ubuntu:16.04

# install apt-utils
RUN apt-get update && apt-get install -y --no-install-recommends apt-utils

# Install some dependencies
RUN apt-get update && apt-get install -y \
        python3 \
        python3-dev \
		python3-tk \
        libpq-dev \
		&& \
	    apt-get clean && \
	    apt-get autoremove


# install python3-pip
RUN apt-get -y install python3-pip

# upgrade pip
RUN pip3 install pip --upgrade


# create a dir config in srv directory the workdir
RUN mkdir /srv/app && mkdir /srv/config

# add configs file to config directory
ADD ./requirements.txt /srv/config/requirements.txt

# install requirements
RUN pip3 install -r /srv/config/requirements.txt

# copy application files

ADD models /srv/app/models

ADD apis /srv/app/apis

ADD entrypoint-flask.sh /srv/app

RUN mkdir /srv/app/data

RUN chmod -R 755 /srv/app/data

# workdir
WORKDIR /srv/app

# entrypoint
ENTRYPOINT ["sh", "/srv/app/entrypoint-flask.sh"]

CMD ["web"]