version: '3.3'

services:
  mongo:
    restart: always
    ports:
      - 27017:27017
    image: mongo
    volumes:
      - ./mongodb/data:/data/db
    hostname: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: breacmpa
      MONGO_INITDB_DATABASE: workflowdb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: breacmpa

  postgres:
    image: postgres:9.6
    environment:
        - POSTGRES_USER=airflow
        - POSTGRES_PASSWORD=airflow
        - POSTGRES_DB=airflow

  webserver:
    image: puckel/docker-airflow:latest
    restart: always
    depends_on:
        - postgres
        - mongo
    environment:
      EXECUTOR: Local
      MONGO_DATABASE: workflowdb
      MONGO_USERNAME: root
      MONGO_PASSWORD: breacmpa
      MONGO_HOST: mongo

    volumes:
        - ./dags:/usr/local/airflow/dags
    ports:
        - "8080:8080"
    command: webserver
    healthcheck:
        test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
        interval: 30s
        timeout: 30s
        retries: 3

  flask:
    depends_on:
      - mongo
    image: workflow-flask
    restart: always
    ports:
      - 5000:5000
    environment:
      MONGO_DATABASE: workflowdb
      MONGO_USERNAME: root
      MONGO_PASSWORD: breacmpa
      MONGO_HOST: mongo

    command: flask