version: '3.3'

services:

   mongo:
     restart: always
     build:
       context: .
       dockerfile: Dockerfile-mongo
     volumes:
       - ./mongodb/data:/data/db
     hostname: mongodb
     environment:
       MONGO_INITDB_ROOT_USERNAME: root
       MONGO_INITDB_ROOT_PASSWORD: breacmpa
       MONGO_INITDB_DATABASE: workflowdb

   mongo-express:
     image: mongo-express
     restart: always
     ports:
       - 8081:8081
     environment:
       ME_CONFIG_MONGODB_ADMINUSERNAME: root
       ME_CONFIG_MONGODB_ADMINPASSWORD: breacmpa
